name: GitHub Actions

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install
              run: npm install
            - name: Unit Tests
              run: npm test
